name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar o .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # 3. Configurar a fonte do NuGet
    - name: Setup NuGet source
      run: |
        if [ $(dotnet nuget list source | grep -c "https://api.nuget.org/v3/index.json") -eq 0 ]; then
          dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
        else
          echo "NuGet source 'nuget.org' já está configurada."
        fi

    # 4. Restaurar dependências do projeto
    - name: Restore dependencies
      run: dotnet restore

    # 5. Instalar Playwright CLI
    - name: Install Playwright CLI
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    # 6. Instalar navegadores do Playwright
    - name: Install Playwright browsers
      run: playwright install

    # 7. Executar os testes
    - name: Run Playwright tests
      run: dotnet test --filter "(Category=VehicleData) | (Category=InsurantData)"
